# Generated by Django 4.2 on 2023-04-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursetitle', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=100)),
                ('coursesection', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
            ],
        )
    ]
